apiVersion: v1
kind: Service
metadata:
  name: my-app-preview
  labels:
    app: my-app
spec:
  selector:
    app: my-app
    version: green  # Auf Green Deployment zeigen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
