apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-rollout
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      rollout: my-app-rollout  # Zusätzliches Label
  strategy:
    type: BlueGreen
    blueGreen:
      activeService: my-app-service    # Service für die aktive (Blue) Version
      previewService: my-app-preview  # Service für die neue (Green) Version
      autoPromotionEnabled: false      # Manuelles Promoten erforderlich
  template:
    metadata:
      labels:
        app: my-app
        rollout: my-app-rollout        # Zusätzliches Label
        version: blue                   # Label für die Blue-Version
    spec:
      containers:
        - name: my-app-container
          image: my-app:1.0.0          # Initiale Version (Blue)
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
