apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
    rollout: my-app-rollout  # Zusätzliches Label
    version: blue              # Selektor für die Blue-Version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Oder NodePort/InCluster je nach Bedarf
